# Generated by Django 2.1.5 on 2019-12-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='news',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
